version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=master
    ports:
      - 5432:5432
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - 6000:80
      - 6001:443
    depends_on:
      - db