version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - 80:80
      - 433:433
    depends_on:
      - postgres